/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: guillaumecrz (https://sketchfab.com/guillaumecrz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ergonomic-mesh-office-chair-cd5ef0305d8545dd8cd934ebb99cf7d5
Title: Ergonomic mesh office chair
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Chair(props) {
  const { nodes, materials } = useGLTF("models/chair.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[431.984, -382.225, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={22.955}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle_Black_PBA_0.geometry}
              material={materials.Black_PBA}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle_Roller_ceramic_0.geometry}
              material={materials.Roller_ceramic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle_Black_painted_metal_0.geometry}
              material={materials.Black_painted_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle_Black_sss_ceramic_0.geometry}
              material={materials.Black_sss_ceramic}
            />
          </group>
          <group
            position={[125.293, -382.225, -419.23]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={22.955}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle001_Black_PBA_0.geometry}
              material={materials.Black_PBA}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle001_Roller_ceramic_0.geometry}
              material={materials.Roller_ceramic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle001_Black_painted_metal_0.geometry}
              material={materials.Black_painted_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle001_Black_sss_ceramic_0.geometry}
              material={materials.Black_sss_ceramic}
            />
          </group>
          <group
            position={[-369.477, -382.225, -259.459]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={22.955}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle002_Black_PBA_0.geometry}
              material={materials.Black_PBA}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle002_Roller_ceramic_0.geometry}
              material={materials.Roller_ceramic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle002_Black_painted_metal_0.geometry}
              material={materials.Black_painted_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle002_Black_sss_ceramic_0.geometry}
              material={materials.Black_sss_ceramic}
            />
          </group>
          <group
            position={[-368.744, -382.225, 260.574]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={22.955}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle003_Black_PBA_0.geometry}
              material={materials.Black_PBA}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle003_Roller_ceramic_0.geometry}
              material={materials.Roller_ceramic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle003_Black_painted_metal_0.geometry}
              material={materials.Black_painted_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle003_Black_sss_ceramic_0.geometry}
              material={materials.Black_sss_ceramic}
            />
          </group>
          <group
            position={[126.094, -382.225, 420.732]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={22.955}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle004_Black_PBA_0.geometry}
              material={materials.Black_PBA}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle004_Roller_ceramic_0.geometry}
              material={materials.Roller_ceramic}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle004_Black_painted_metal_0.geometry}
              material={materials.Black_painted_metal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Roulette_socle004_Black_sss_ceramic_0.geometry}
              material={materials.Black_sss_ceramic}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Structure_Black_painted_metal_0.geometry}
            material={materials.Black_painted_metal}
            position={[-226.098, 287.275, 0.452]}
            rotation={[-Math.PI / 2, 1.396, 0]}
            scale={[104.527, 127.755, 127.097]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Back_knob_Black_painted_metal_0.geometry}
            material={materials.Black_painted_metal}
            position={[-294.437, 241.325, -0.04]}
            rotation={[-1.029, -1.56, 2.211]}
            scale={38.349}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cushion_plastic_base_Black_PBA_0.geometry}
            material={materials.Black_PBA}
            position={[-217.563, 236.159, 0]}
            rotation={[-Math.PI / 2, 0.006, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder007_Black_PBA_0.geometry}
            material={materials.Black_PBA}
            position={[-291.398, 241.008, -0.061]}
            rotation={[-1.029, -1.56, 2.211]}
            scale={[38.349, 38.349, 29.379]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cushion_Black_rubber_0.geometry}
            material={materials.Black_rubber}
            position={[-204.158, 236.159, 0]}
            rotation={[-Math.PI / 2, 0.006, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Joints_Black_painted_metal_0.geometry}
            material={materials.Black_painted_metal}
            position={[-106.715, 289.519, -71.327]}
            rotation={[-Math.PI / 2, 1.396, 0]}
            scale={[104.527, 127.755, 127.097]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Arms_Material_0.geometry}
            material={materials.Material}
            position={[-220.56, 268.163, 230.708]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={16.655}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Armrest_base_Black_painted_metal_0.geometry}
            material={materials.Black_painted_metal}
            position={[-220.56, 268.163, 230.708]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Hard_cushions_Black_painted_metal_0.geometry}
            material={materials.Black_painted_metal}
            position={[-220.56, 268.163, 230.708]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Back_outline_frame_Black_painted_metal_0.geometry}
            material={materials.Black_painted_metal}
            position={[-226.098, 287.275, 0.452]}
            rotation={[-Math.PI / 2, 1.396, 0]}
            scale={[104.527, 127.755, 127.097]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Back_mesh__Mesh_0.geometry}
            material={materials.Mesh}
            position={[-222.889, 287.841, 0.452]}
            rotation={[-Math.PI / 2, 1.396, 0]}
            scale={[104.527, 127.755, 127.097]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.Back_to_mechanism_joints_Black_painted_metal_0.geometry
            }
            material={materials.Black_painted_metal}
            position={[-226.098, 287.275, 0.452]}
            rotation={[-Math.PI / 2, 1.396, 0]}
            scale={[104.527, 127.755, 127.097]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mechanism_base_Material_0.geometry}
            material={materials.Material}
            position={[0, 348.671, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Front_knob_Black_painted_metal_0.geometry}
            material={materials.Black_painted_metal}
            position={[220.745, 27.226, 0]}
            rotation={[1.503, 1.488, -1.405]}
            scale={25.73}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Handle_Black_PBA_0.geometry}
            material={materials.Black_PBA}
            position={[-108.865, -6.605, 238.331]}
            rotation={[-1.454, 0.347, -0.04]}
            scale={8.065}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Handle_rod_Metal_0.geometry}
            material={materials.material_0}
            position={[-112.359, -27.445, 141.554]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={10.773}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Front_knob_screw_Metal_0.geometry}
            material={materials.material_0}
            position={[219.982, 27.226, 0]}
            rotation={[1.503, 1.488, -1.405]}
            scale={25.73}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Seat_outline_frame_Black_PBA_0.geometry}
            material={materials.Black_PBA}
            position={[-51.498, 124.202, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Seat_mesh_Mesh_0.geometry}
            material={materials.Mesh}
            position={[-51.498, 137.191, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Front_seat_to_mechanism_joints_Black_PBA_0.geometry}
            material={materials.Black_PBA}
            position={[-51.498, 124.202, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Back_seat_to_mechanism_joints_Black_PBA_0.geometry}
            material={materials.Black_PBA}
            position={[-51.498, 124.202, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Etoile_Black_PBA_0.geometry}
            material={materials.Black_PBA}
            position={[0, -317.295, 0]}
            rotation={[-Math.PI / 2, 0, -1.257]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_Material_0.geometry}
            material={materials.Material}
            position={[2.237, -182.06, -1.491]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_Black_PBA_0.geometry}
            material={materials.Black_PBA}
            position={[2.237, -27.217, -1.491]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_Black_rubber_0.geometry}
            material={materials.Black_rubber}
            position={[2.237, -137.775, -1.491]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={105.513}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_Metal_0.geometry}
            material={materials.material_0}
            position={[-289.105, 241.325, -0.04]}
            rotation={[-1.029, -1.56, 2.211]}
            scale={38.349}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/chair.glb");
