/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mfkffzl (https://sketchfab.com/mfkffzl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/keyboard-backlit-keyboard-514594b374d94c5f9f47d54ae2cad2b1
Title: keyboard (backlit keyboard)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Keyboard(props) {
  const { nodes, materials } = useGLTF("models/keyboard_backlit_keyboard.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-1.385, 1.264, 0.69]}
        rotation={[-3.062, 0, 0]}
        scale={0.104}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_334.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_335.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_336.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_337.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials["Material.003"]}
        position={[0, 1.256, -0.01]}
        rotation={[0.069, 0, 0]}
        scale={[2.964, 0.054, 0.829]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.material_0}
        position={[-2.752, 1.469, -0.584]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.material_0}
        position={[-2.29, 1.469, -0.584]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.material_0}
        position={[-1.142, 1.469, -0.584]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.material_0}
        position={[0.011, 1.469, -0.584]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.material_0}
        position={[1.105, 1.469, -0.584]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.material_0}
        position={[-2.756, 1.449, -0.3]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.material_0}
        position={[-2.414, 1.431, -0.038]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials.material_0}
        position={[-2.306, 1.414, 0.21]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials.material_0}
        position={[-2.203, 1.397, 0.457]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials.material_0}
        position={[1.105, 1.45, -0.314]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials.material_0}
        position={[1.105, 1.433, -0.06]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials.material_0}
        position={[2.403, 1.381, 0.679]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials.material_0}
        position={[1.126, 1.381, 0.68]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials.material_0}
        position={[-2.595, 1.397, 0.457]}
        rotation={[0.069, 0, 0]}
        scale={[0.25, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_34.geometry}
        material={materials.material_0}
        position={[0.593, 1.397, 0.457]}
        rotation={[0.069, 0, 0]}
        scale={[-0.293, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_36.geometry}
        material={materials.material_0}
        position={[-1.106, 1.381, 0.685]}
        rotation={[0.069, 0, 0]}
        scale={[-0.831, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_38.geometry}
        material={materials.material_0}
        position={[-2.703, 1.431, -0.038]}
        rotation={[0.069, 0, 0]}
        scale={[0.144, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_40.geometry}
        material={materials.material_0}
        position={[-2.66, 1.414, 0.207]}
        rotation={[0.069, 0, 0]}
        scale={[0.189, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_42.geometry}
        material={materials.material_0}
        position={[2.055, 1.381, 0.68]}
        rotation={[0.069, 0, 0]}
        scale={[0.21, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_44.geometry}
        material={materials.material_0}
        position={[-2.362, 1.381, 0.683]}
        rotation={[0.069, 0, 0]}
        scale={[0.103, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_46.geometry}
        material={materials.material_0}
        position={[-2.082, 1.381, 0.683]}
        rotation={[0.069, 0, 0]}
        scale={[0.103, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_48.geometry}
        material={materials.material_0}
        position={[-0.13, 1.381, 0.683]}
        rotation={[0.069, 0, 0]}
        scale={[0.103, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_50.geometry}
        material={materials.material_0}
        position={[0.137, 1.381, 0.683]}
        rotation={[0.069, 0, 0]}
        scale={[0.103, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_52.geometry}
        material={materials.material_0}
        position={[0.415, 1.381, 0.683]}
        rotation={[0.069, 0, 0]}
        scale={[0.103, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_54.geometry}
        material={materials["Material.013"]}
        position={[0.733, 1.381, 0.678]}
        rotation={[0.069, 0, 0]}
        scale={[0.149, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_56.geometry}
        material={materials.material_0}
        position={[0.651, 1.45, -0.303]}
        rotation={[0.069, 0, 0]}
        scale={[0.221, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_58.geometry}
        material={materials.material_0}
        position={[0.682, 1.43, -0.038]}
        rotation={[0.069, 0, 0]}
        scale={[0.189, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_60.geometry}
        material={materials.material_0}
        position={[2.634, 1.39, 0.557]}
        rotation={[-3.072, 1.56, Math.PI]}
        scale={[0.212, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_62.geometry}
        material={materials["Material.012"]}
        position={[-2.681, 1.381, 0.678]}
        rotation={[0.069, 0, 0]}
        scale={[0.159, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_64.geometry}
        material={materials.material_0}
        position={[1.369, 1.398, 0.437]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_66.geometry}
        material={materials.material_0}
        position={[1.937, 1.447, -0.261]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_68.geometry}
        material={materials.material_0}
        position={[1.937, 1.429, -0.014]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_70.geometry}
        material={materials.material_0}
        position={[1.937, 1.413, 0.226]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_72.geometry}
        material={materials.material_0}
        position={[1.937, 1.397, 0.459]}
        rotation={[0.069, 0, 0]}
        scale={[0.092, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_74.geometry}
        material={materials.material_0}
        position={[2.634, 1.422, 0.091]}
        rotation={[-3.072, 1.56, Math.PI]}
        scale={[0.212, 0.049, 0.092]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_76.geometry}
        material={materials["Material.014"]}
        position={[2.278, 1.351, -0.578]}
        rotation={[0.069, 0, 0]}
        scale={[-0.372, 0.03, 0.103]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_78.geometry}
        material={materials.material_0}
        position={[-2.757, 1.378, -0.596]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_80.geometry}
        material={materials.material_0}
        position={[-2.29, 1.388, -0.586]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_82.geometry}
        material={materials.material_0}
        position={[-1.143, 1.388, -0.586]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_84.geometry}
        material={materials.material_0}
        position={[0.004, 1.388, -0.586]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_86.geometry}
        material={materials.material_0}
        position={[1.115, 1.388, -0.586]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_88.geometry}
        material={materials.material_0}
        position={[1.115, 1.369, -0.315]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_90.geometry}
        material={materials.material_0}
        position={[1.115, 1.351, -0.062]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_92.geometry}
        material={materials.material_0}
        position={[1.115, 1.3, 0.671]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_94.geometry}
        material={materials.material_0}
        position={[1.912, 1.315, 0.462]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_96.geometry}
        material={materials.material_0}
        position={[1.912, 1.331, 0.235]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_98.geometry}
        material={materials.material_0}
        position={[1.912, 1.348, -0.01]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_100.geometry}
        material={materials.material_0}
        position={[1.912, 1.365, -0.263]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_102.geometry}
        material={materials.material_0}
        position={[-2.772, 1.368, -0.298]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_104.geometry}
        material={materials.material_0}
        position={[-2.386, 1.35, -0.045]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_106.geometry}
        material={materials.material_0}
        position={[-2.281, 1.332, 0.209]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_108.geometry}
        material={materials.material_0}
        position={[-2.185, 1.316, 0.444]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_110.geometry}
        material={materials.material_0}
        position={[-2.343, 1.3, 0.671]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_112.geometry}
        material={materials.material_0}
        position={[-0.128, 1.3, 0.671]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_114.geometry}
        material={materials.material_0}
        position={[0.73, 1.3, 0.671]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_116.geometry}
        material={materials.material_0}
        position={[2.062, 1.301, 0.669]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_118.geometry}
        material={materials.material_0}
        position={[2.408, 1.301, 0.669]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_120.geometry}
        material={materials.material_0}
        position={[2.639, 1.309, 0.554]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_122.geometry}
        material={materials.material_0}
        position={[0.748, 1.341, 0.08]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_124.geometry}
        material={materials.material_0}
        position={[0.572, 1.315, 0.463]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_126.geometry}
        material={materials.material_0}
        position={[0.663, 1.368, -0.302]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_128.geometry}
        material={materials.material_0}
        position={[-2.589, 1.316, 0.45]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_130.geometry}
        material={materials.material_0}
        position={[-2.68, 1.301, 0.669]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_132.geometry}
        material={materials.material_0}
        position={[-2.662, 1.333, 0.202]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_134.geometry}
        material={materials.material_0}
        position={[-2.705, 1.35, -0.047]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_136.geometry}
        material={materials.material_0}
        position={[-1.822, 1.299, 0.686]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_138.geometry}
        material={materials.material_0}
        position={[-1.088, 1.299, 0.686]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_140.geometry}
        material={materials.material_0}
        position={[-0.412, 1.299, 0.686]}
        rotation={[0.069, 0, 0]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_142.geometry}
        material={materials["Material.004"]}
        position={[0.009, 1.207, -0.662]}
        rotation={[-2.912, 0, -1.571]}
        scale={[0.086, 2.906, 0.166]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_144.geometry}
        material={materials["Material.005"]}
        position={[-2.791, 1.146, 0.706]}
        rotation={[0.076, 0, 0]}
        scale={[0.086, 0.01, 0.037]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_146.geometry}
        material={materials["Material.005"]}
        position={[2.812, 1.144, 0.706]}
        rotation={[0.08, 0, 0]}
        scale={[0.086, 0.01, 0.037]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_148.geometry}
        material={materials["Material.005"]}
        position={[-2.791, 1.115, -0.631]}
        rotation={[0.076, 0, 0]}
        scale={[0.086, 0.01, 0.037]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_150.geometry}
        material={materials["Material.005"]}
        position={[2.829, 1.112, -0.631]}
        rotation={[0.076, 0, 0]}
        scale={[0.086, 0.01, 0.037]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_152.geometry}
        material={materials["Material.006"]}
        position={[1.936, 1.329, -0.262]}
        rotation={[0.07, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_154.geometry}
        material={materials["Material.006"]}
        position={[2.171, 1.329, -0.262]}
        rotation={[0.07, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_156.geometry}
        material={materials["Material.006"]}
        position={[2.403, 1.329, -0.262]}
        rotation={[0.07, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_158.geometry}
        material={materials["Material.006"]}
        position={[2.63, 1.329, -0.262]}
        rotation={[0.07, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_160.geometry}
        material={materials["Material.006"]}
        position={[1.932, 1.311, -0.015]}
        rotation={[0.07, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_162.geometry}
        material={materials["Material.006"]}
        position={[1.932, 1.294, 0.224]}
        rotation={[0.07, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_164.geometry}
        material={materials["Material.006"]}
        position={[1.932, 1.279, 0.461]}
        rotation={[0.07, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_166.geometry}
        material={materials["Material.006"]}
        position={[2.401, 1.263, 0.684]}
        rotation={[0.07, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_168.geometry}
        material={materials["Material.006"]}
        position={[2.047, 1.263, 0.684]}
        rotation={[0.07, 0, 0]}
        scale={[0.221, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_170.geometry}
        material={materials["Material.006"]}
        position={[2.633, 1.271, 0.564]}
        rotation={[0.07, 0, 0]}
        scale={[0.106, 0.107, 0.226]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_172.geometry}
        material={materials["Material.006"]}
        position={[2.633, 1.303, 0.105]}
        rotation={[0.07, 0, 0]}
        scale={[0.106, 0.107, 0.226]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_174.geometry}
        material={materials["Material.007"]}
        position={[1.604, 1.266, 0.681]}
        rotation={[0.082, 0, 0]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_176.geometry}
        material={materials["Material.007"]}
        position={[-2.169, 1.321, -0.04]}
        rotation={[0.082, 0, 0]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_178.geometry}
        material={materials["Material.007"]}
        position={[1.617, 1.331, -0.31]}
        rotation={[0.073, 0, 0]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_180.geometry}
        material={materials["Material.007"]}
        position={[1.617, 1.351, -0.572]}
        rotation={[0.087, 0, 0]}
        scale={[0.107, 0.107, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_182.geometry}
        material={materials["Material.008"]}
        position={[1.37, 1.264, 0.681]}
        rotation={[0.065, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_184.geometry}
        material={materials["Material.008"]}
        position={[1.37, 1.279, 0.441]}
        rotation={[0.068, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_186.geometry}
        material={materials["Material.008"]}
        position={[1.364, 1.317, -0.057]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_188.geometry}
        material={materials["Material.008"]}
        position={[1.363, 1.336, -0.312]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_190.geometry}
        material={materials["Material.008"]}
        position={[1.364, 1.354, -0.582]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_192.geometry}
        material={materials["Material.008"]}
        position={[1.102, 1.336, -0.312]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_194.geometry}
        material={materials["Material.008"]}
        position={[1.103, 1.354, -0.582]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_196.geometry}
        material={materials["Material.008"]}
        position={[1.101, 1.317, -0.057]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_198.geometry}
        material={materials["Material.008"]}
        position={[1.122, 1.264, 0.681]}
        rotation={[0.065, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_200.geometry}
        material={materials["Material.008"]}
        position={[0.002, 1.331, -0.3]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_202.geometry}
        material={materials["Material.008"]}
        position={[0.076, 1.313, -0.039]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_204.geometry}
        material={materials["Material.008"]}
        position={[0.183, 1.296, 0.211]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_206.geometry}
        material={materials["Material.008"]}
        position={[0.119, 1.354, 0.456]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_208.geometry}
        material={materials["Material.008"]}
        position={[-0.133, 1.265, 0.685]}
        rotation={[0.074, 0, 0]}
        scale={[0.116, 0.105, 0.105]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_210.geometry}
        material={materials["Material.008"]}
        position={[0.728, 1.265, 0.685]}
        rotation={[0.074, 0, 0]}
        scale={[0.17, 0.105, 0.105]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_212.geometry}
        material={materials["Material.008"]}
        position={[0.595, 1.279, 0.459]}
        rotation={[0.074, 0, 0]}
        scale={[0.316, 0.105, 0.105]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_214.geometry}
        material={materials["Material.008"]}
        position={[0.009, 1.354, -0.58]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_216.geometry}
        material={materials["Material.008"]}
        position={[0.515, 1.354, -0.58]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_218.geometry}
        material={materials["Material.008"]}
        position={[0.748, 1.313, 0.142]}
        rotation={[0.074, 0, 0]}
        scale={[0.15, 0.105, 0.105]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_220.geometry}
        material={materials["Material.009"]}
        position={[-0.249, 1.33, -0.3]}
        rotation={[0.034, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_222.geometry}
        material={materials["Material.009"]}
        position={[-0.172, 1.313, -0.041]}
        rotation={[0.06, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_224.geometry}
        material={materials["Material.009"]}
        position={[-0.062, 1.297, 0.21]}
        rotation={[0.048, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_226.geometry}
        material={materials["Material.009"]}
        position={[-0.133, 1.279, 0.459]}
        rotation={[0.065, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_228.geometry}
        material={materials["Material.009"]}
        position={[-0.372, 1.351, -0.585]}
        rotation={[0.066, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_230.geometry}
        material={materials["Material.009"]}
        position={[-0.631, 1.353, -0.585]}
        rotation={[0.038, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_232.geometry}
        material={materials["Material.009"]}
        position={[-0.5, 1.331, -0.303]}
        rotation={[0.063, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_234.geometry}
        material={materials["Material.009"]}
        position={[-0.423, 1.313, -0.038]}
        rotation={[0.068, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_236.geometry}
        material={materials["Material.009"]}
        position={[-0.31, 1.297, 0.21]}
        rotation={[0.051, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_238.geometry}
        material={materials["Material.009"]}
        position={[-0.395, 1.279, 0.459]}
        rotation={[0.082, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_240.geometry}
        material={materials["Material.010"]}
        position={[-0.566, 1.295, 0.209]}
        rotation={[0.039, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_242.geometry}
        material={materials["Material.010"]}
        position={[-0.648, 1.28, 0.455]}
        rotation={[0.068, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_244.geometry}
        material={materials["Material.010"]}
        position={[-0.921, 1.313, -0.037]}
        rotation={[0.059, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_246.geometry}
        material={materials["Material.010"]}
        position={[-1.001, 1.334, -0.295]}
        rotation={[0.03, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_248.geometry}
        material={materials["Material.010"]}
        position={[-0.886, 1.357, -0.584]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_250.geometry}
        material={materials["Material.010"]}
        position={[-0.818, 1.299, 0.209]}
        rotation={[0.019, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_252.geometry}
        material={materials["Material.010"]}
        position={[-0.673, 1.313, -0.037]}
        rotation={[0.079, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_254.geometry}
        material={materials["Material.010"]}
        position={[-0.753, 1.333, -0.295]}
        rotation={[0.045, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_256.geometry}
        material={materials["Material.010"]}
        position={[-0.91, 1.28, 0.455]}
        rotation={[0.045, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_258.geometry}
        material={materials["Material.008"]}
        position={[0.648, 1.331, -0.3]}
        rotation={[0.074, 0, 0]}
        scale={[0.24, 0.105, 0.105]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_260.geometry}
        material={materials["Material.011"]}
        position={[-1.172, 1.289, 0.458]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_262.geometry}
        material={materials["Material.011"]}
        position={[-1.062, 1.302, 0.217]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_264.geometry}
        material={materials["Material.011"]}
        position={[-1.252, 1.333, -0.295]}
        rotation={[0.039, 0, 0]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_266.geometry}
        material={materials["Material.011"]}
        position={[-1.145, 1.361, -0.575]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_268.geometry}
        material={materials["Material.011"]}
        position={[-1.167, 1.315, -0.039]}
        rotation={[0.045, 0, 0]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_270.geometry}
        material={materials["Material.010"]}
        position={[-1.309, 1.302, 0.209]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_272.geometry}
        material={materials["Material.010"]}
        position={[-1.434, 1.278, 0.455]}
        rotation={[0.051, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_274.geometry}
        material={materials["Material.010"]}
        position={[-1.419, 1.324, -0.037]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_276.geometry}
        material={materials["Material.010"]}
        position={[-1.503, 1.333, -0.295]}
        rotation={[0.039, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_278.geometry}
        material={materials["Material.010"]}
        position={[-1.525, 1.351, -0.584]}
        rotation={[0.08, 0, 0]}
        scale={0.106}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_280.geometry}
        material={materials["Material.009"]}
        position={[-1.753, 1.333, -0.295]}
        rotation={[0.04, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_282.geometry}
        material={materials["Material.009"]}
        position={[-1.668, 1.313, -0.038]}
        rotation={[0.059, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_284.geometry}
        material={materials["Material.009"]}
        position={[-1.561, 1.297, 0.21]}
        rotation={[0.053, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_286.geometry}
        material={materials["Material.009"]}
        position={[-1.685, 1.278, 0.459]}
        rotation={[0.074, 0, 0]}
        scale={0.104}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_288.geometry}
        material={materials["Material.008"]}
        position={[-1.953, 1.279, 0.456]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_290.geometry}
        material={materials["Material.008"]}
        position={[-1.816, 1.296, 0.211]}
        rotation={[0.06, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_292.geometry}
        material={materials["Material.008"]}
        position={[-1.918, 1.313, -0.039]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_294.geometry}
        material={materials["Material.008"]}
        position={[-2, 1.331, -0.3]}
        rotation={[0.063, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_296.geometry}
        material={materials["Material.008"]}
        position={[-1.782, 1.354, -0.58]}
        rotation={[0.074, 0, 0]}
        scale={0.105}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_298.geometry}
        material={materials["Material.007"]}
        position={[1.613, 1.321, -0.051]}
        rotation={[0.082, 0, 0]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_300.geometry}
        material={materials["Material.007"]}
        position={[-2.204, 1.281, 0.464]}
        rotation={[0.082, 0, 0]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_302.geometry}
        material={materials["Material.007"]}
        position={[-2.082, 1.266, 0.691]}
        rotation={[0.082, 0, 0]}
        scale={[0.123, 0.107, 0.107]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_304.geometry}
        material={materials["Material.007"]}
        position={[-2.057, 1.295, 0.21]}
        rotation={[0.066, 0, 0]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_306.geometry}
        material={materials["Material.007"]}
        position={[-2.256, 1.331, -0.294]}
        rotation={[0.073, 0, 0]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_308.geometry}
        material={materials["Material.007"]}
        position={[-2.032, 1.351, -0.583]}
        rotation={[0.078, 0, 0]}
        scale={[0.107, 0.107, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_310.geometry}
        material={materials["Material.006"]}
        position={[-2.362, 1.263, 0.684]}
        rotation={[0.07, 0, 0]}
        scale={[0.118, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_312.geometry}
        material={materials["Material.006"]}
        position={[-2.681, 1.263, 0.684]}
        rotation={[0.07, 0, 0]}
        scale={[0.179, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_314.geometry}
        material={materials["Material.006"]}
        position={[-2.597, 1.28, 0.462]}
        rotation={[0.07, 0, 0]}
        scale={[0.27, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_316.geometry}
        material={materials["Material.006"]}
        position={[-2.597, 1.28, 0.462]}
        rotation={[0.07, 0, 0]}
        scale={[0.27, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_318.geometry}
        material={materials["Material.006"]}
        position={[-2.307, 1.302, 0.215]}
        rotation={[0.07, 0, 0]}
        scale={[0.11, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_320.geometry}
        material={materials["Material.006"]}
        position={[-2.414, 1.313, -0.04]}
        rotation={[0.07, 0, 0]}
        scale={[0.11, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_322.geometry}
        material={materials["Material.006"]}
        position={[-2.502, 1.331, -0.299]}
        rotation={[0.07, 0, 0]}
        scale={[0.11, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_324.geometry}
        material={materials["Material.006"]}
        position={[-2.292, 1.351, -0.587]}
        rotation={[0.07, 0, 0]}
        scale={[0.11, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_326.geometry}
        material={materials["Material.006"]}
        position={[-2.748, 1.351, -0.578]}
        rotation={[0.07, 0, 0]}
        scale={[0.11, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_328.geometry}
        material={materials["Material.006"]}
        position={[-2.751, 1.331, -0.299]}
        rotation={[0.07, 0, 0]}
        scale={[0.11, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_330.geometry}
        material={materials["Material.006"]}
        position={[-2.652, 1.295, 0.215]}
        rotation={[0.07, 0, 0]}
        scale={[0.209, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_332.geometry}
        material={materials["Material.006"]}
        position={[-2.706, 1.313, -0.04]}
        rotation={[0.07, 0, 0]}
        scale={[0.163, 0.106, 0.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_339.geometry}
        material={materials["Material.015"]}
        position={[2.021, 1.382, -0.621]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.021, 0.004, 0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_341.geometry}
        material={materials["Material.015"]}
        position={[2.276, 1.382, -0.621]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.021, 0.004, 0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_343.geometry}
        material={materials["Material.015"]}
        position={[2.556, 1.382, -0.621]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.021, 0.004, 0.006]}
      />
    </group>
  );
}

useGLTF.preload("models/keyboard_backlit_keyboard.glb");