/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Source: https://sketchfab.com/3d-models/mouse-ef5398bffec6477c9443677d5c57177c
Title: Mouse
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mouse(props) {
  const { nodes, materials } = useGLTF("models/mouse.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface5_MAT_Plastic_0.geometry}
          material={materials.MAT_Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface2_MAT_Emission_0.geometry}
          material={materials.MAT_Emission}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BOTON_CENTRAL_MAT_Plastic_0.geometry}
          material={materials.MAT_Plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface4_MAT_Details_0.geometry}
          material={materials.MAT_Details}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/mouse.glb");